# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/penultimo/Projects/Facultate/FC/fractali-opencl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/penultimo/Projects/Facultate/FC/fractali-opencl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/penultimo/Projects/Facultate/FC/fractali-opencl/CMakeFiles /home/penultimo/Projects/Facultate/FC/fractali-opencl/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/penultimo/Projects/Facultate/FC/fractali-opencl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PFract

# Build rule for target.
PFract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PFract
.PHONY : PFract

# fast build rule for target.
PFract/fast:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/build
.PHONY : PFract/fast

CLCompositor.o: CLCompositor.cpp.o

.PHONY : CLCompositor.o

# target to build an object file
CLCompositor.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CLCompositor.cpp.o
.PHONY : CLCompositor.cpp.o

CLCompositor.i: CLCompositor.cpp.i

.PHONY : CLCompositor.i

# target to preprocess a source file
CLCompositor.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CLCompositor.cpp.i
.PHONY : CLCompositor.cpp.i

CLCompositor.s: CLCompositor.cpp.s

.PHONY : CLCompositor.s

# target to generate assembly for a file
CLCompositor.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CLCompositor.cpp.s
.PHONY : CLCompositor.cpp.s

CPPCompositor.o: CPPCompositor.cpp.o

.PHONY : CPPCompositor.o

# target to build an object file
CPPCompositor.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CPPCompositor.cpp.o
.PHONY : CPPCompositor.cpp.o

CPPCompositor.i: CPPCompositor.cpp.i

.PHONY : CPPCompositor.i

# target to preprocess a source file
CPPCompositor.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CPPCompositor.cpp.i
.PHONY : CPPCompositor.cpp.i

CPPCompositor.s: CPPCompositor.cpp.s

.PHONY : CPPCompositor.s

# target to generate assembly for a file
CPPCompositor.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/CPPCompositor.cpp.s
.PHONY : CPPCompositor.cpp.s

Compositor.o: Compositor.cpp.o

.PHONY : Compositor.o

# target to build an object file
Compositor.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Compositor.cpp.o
.PHONY : Compositor.cpp.o

Compositor.i: Compositor.cpp.i

.PHONY : Compositor.i

# target to preprocess a source file
Compositor.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Compositor.cpp.i
.PHONY : Compositor.cpp.i

Compositor.s: Compositor.cpp.s

.PHONY : Compositor.s

# target to generate assembly for a file
Compositor.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Compositor.cpp.s
.PHONY : Compositor.cpp.s

View.o: View.cpp.o

.PHONY : View.o

# target to build an object file
View.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/View.cpp.o
.PHONY : View.cpp.o

View.i: View.cpp.i

.PHONY : View.i

# target to preprocess a source file
View.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/View.cpp.i
.PHONY : View.cpp.i

View.s: View.cpp.s

.PHONY : View.s

# target to generate assembly for a file
View.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/View.cpp.s
.PHONY : View.cpp.s

Window.o: Window.cpp.o

.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/Window.cpp.s
.PHONY : Window.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PFract.dir/build.make CMakeFiles/PFract.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PFract"
	@echo "... CLCompositor.o"
	@echo "... CLCompositor.i"
	@echo "... CLCompositor.s"
	@echo "... CPPCompositor.o"
	@echo "... CPPCompositor.i"
	@echo "... CPPCompositor.s"
	@echo "... Compositor.o"
	@echo "... Compositor.i"
	@echo "... Compositor.s"
	@echo "... View.o"
	@echo "... View.i"
	@echo "... View.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

